export const avatars = [
  "../../../src/assets/Avatars/avatar_1.png",
  "../../../src/assets/Avatars/avatar_2.png",
  "../../../src/assets/Avatars/avatar_3.png",
  "../../../src/assets/Avatars/avatar_4.png",
  "../../../src/assets/Avatars/avatar_5.png",
  "../../../src/assets/Avatars/avatar_6.png",
  "../../../src/assets/Avatars/avatar_7.png",
  "../../../src/assets/Avatars/avatar_8.png",
  "../../../src/assets/Avatars/avatar_9.png",
  "../../../src/assets/Avatars/avatar_10.png",
  "../../../src/assets/Avatars/avatar_11.png",
  "../../../src/assets/Avatars/avatar_12.png",
  "../../../src/assets/Avatars/avatar_13.png",
  "../../../src/assets/Avatars/avatar_14.png",
  "../../../src/assets/Avatars/avatar_15.png",
];
